"""2026夏アニメの初期データ投入"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from store import save_works, slugify, share_slugify

sys.stdout.reconfigure(encoding='utf-8')

SEASON = '2026-summer'

# X（Twitter）はURL内の非ASCII文字でリンクが切れるため、ASCII専用の share_slug を付与
SHARE_SLUGS = {
    '無職転生Ⅲ ～異世界行ったら本気だす～': 'mushoku-tensei-3',
    '幼女戦記Ⅱ': 'youjo-senki-2',
    'Re:ゼロから始める異世界生活 4th season 奪還編': 're-zero-4th-dakkan',
    'ぐらんぶる Season 3': 'grand-blue-season-3',
    'BLEACH 千年血戦篇-禍進譚-': 'bleach-senbankessen-kashintan',
    '君のことが大大大大大好きな100人の彼女 第3期': 'hyakkano-3',
    '逃げ上手の若君 第二期': 'nige-jouzu-2',
    '骸骨騎士様、只今異世界へお出掛け中Ⅱ': 'gaikotsu-kishi-2',
    '乙女ゲー世界はモブに厳しい世界です2': 'mobuseka-2',
    '片田舎のおっさん、剣聖になるⅡ': 'katainaka-kensei-2',
    'きみが死ぬまで恋をしたい': 'kimi-shinu',
    '株式会社マジルミエ 第2期': 'magilumiere-2',
    '正反対な君と僕 第2期': 'seihantaiteki-2',
    '攻殻機動隊 THE GHOST IN THE SHELL': 'ghost-in-the-shell',
    '天幕のジャードゥーガル': 'tenmaku-jadougal',
    'クレバテスⅡ-魔獣の王と偽りの勇者伝承-': 'clevatess-2',
    'スーパーの裏でヤニ吸うふたり': 'super-yani-2',
    '追放された転生重騎士はゲーム知識で無双する': 'tsuihou-juukishi',
    'ワールド イズ ダンシング': 'world-is-dancing',
    '二十世紀電氣目録-ユーレカ・エヴリカ-': '20seiki-eureka',
    'ワンパンマン 第3期': 'onepunch-man-3',
}

# 人気作中心に原作情報を手動で付与（後から編集・Annict同期可）
WORKS = [
    {
        'title': '無職転生Ⅲ ～異世界行ったら本気だす～',
        'source_type': 'light_novel',
        'source_title': '無職転生 ～異世界行ったら本気だす～',
        'volumes_anime': '第3期は第12巻以降の内容（第1・2期は1〜11巻相当）',
        'read_order': '小説1巻から順に。アニメ未視聴なら1巻から読むのがおすすめ',
        'amazon_search': '無職転生 ラノベ',
        'tags': ['異世界', 'ファンタジー'],
        'watchers_count': 9999,
    },
    {
        'title': '幼女戦記Ⅱ',
        'source_type': 'light_novel',
        'source_title': '幼女戦記',
        'volumes_anime': '第2期は第1期の続き（ラノベ中盤〜）',
        'read_order': '1巻から。第1期を見た場合は該当巻から',
        'amazon_search': '幼女戦記 ラノベ',
        'tags': ['異世界', 'ミリタリー'],
        'watchers_count': 9500,
    },
    {
        'title': 'Re:ゼロから始める異世界生活 4th season 奪還編',
        'source_type': 'light_novel',
        'source_title': 'Re:ゼロから始める異世界生活',
        'volumes_anime': '奪還編は小説後半アーク（巻数は放送に合わせて要確認）',
        'read_order': 'アニメ1期から見た人は、対応する巻から読む',
        'amazon_search': 'Reゼロ ラノベ',
        'tags': ['異世界', 'ダーク'],
        'watchers_count': 9800,
    },
    {
        'title': 'ぐらんぶる Season 3',
        'source_type': 'manga',
        'source_title': 'ぐらんぶる',
        'volumes_anime': '第3期は漫画中盤〜（各期で数巻分相当）',
        'read_order': '漫画1巻から。ダイビングコメディ',
        'amazon_search': 'ぐらんぶる 漫画',
        'tags': ['コメディ', 'スポーツ'],
        'watchers_count': 8800,
    },
    {
        'title': 'BLEACH 千年血戦篇-禍進譚-',
        'source_type': 'manga',
        'source_title': 'BLEACH',
        'volumes_anime': '千年血戦篇の後半パート',
        'read_order': '漫画は完結済み。アニメのみならそのまま視聴可',
        'amazon_search': 'BLEACH 全巻',
        'tags': ['バトル', '少年漫画'],
        'watchers_count': 9200,
    },
    {
        'title': '君のことが大大大大大好きな100人の彼女 第3期',
        'source_type': 'manga',
        'source_title': '君のことが大大大大大好きな100人の彼女',
        'volumes_anime': '第3期は漫画続編エピソード',
        'read_order': '漫画1巻からがおすすめ',
        'amazon_search': '100人の彼女 漫画',
        'tags': ['ラブコメ', 'ギャグ'],
        'watchers_count': 8500,
    },
    {
        'title': '逃げ上手の若君 第二期',
        'source_type': 'manga',
        'source_title': '逃げ上手の若君',
        'volumes_anime': '第2期は第1期の続き',
        'read_order': '漫画1巻から',
        'amazon_search': '逃げ上手の若君 漫画',
        'tags': ['歴史', 'コメディ'],
        'watchers_count': 8200,
    },
    {
        'title': '骸骨騎士様、只今異世界へお出掛け中Ⅱ',
        'source_type': 'light_novel',
        'source_title': '骸骨騎士様、只今異世界へお出掛け中',
        'volumes_anime': '第2期はラノベ続編',
        'read_order': '1巻から。異世界ゆるふわ系',
        'amazon_search': '骸骨騎士様 ラノベ',
        'tags': ['異世界', 'ファンタジー'],
        'watchers_count': 7500,
    },
    {
        'title': '乙女ゲー世界はモブに厳しい世界です2',
        'source_type': 'light_novel',
        'source_title': '乙女ゲー世界はモブに厳しい世界です',
        'volumes_anime': '第2期はラノベ中盤〜',
        'read_order': '1巻から読むと設定がわかりやすい',
        'amazon_search': '乙女ゲー世界はモブに厳しい世界です ラノベ',
        'tags': ['異世界', '乙女ゲー'],
        'watchers_count': 7800,
    },
    {
        'title': '片田舎のおっさん、剣聖になるⅡ',
        'source_type': 'light_novel',
        'source_title': '片田舎のおっさん、剣聖になる',
        'volumes_anime': '第2期はラノベ続編',
        'read_order': '1巻から',
        'amazon_search': '片田舎のおっさん 剣聖 ラノベ',
        'tags': ['ファンタジー', 'バトル'],
        'watchers_count': 7600,
    },
    {
        'title': 'きみが死ぬまで恋をしたい',
        'source_type': 'manga',
        'source_title': 'きみが死ぬまで恋をしたい',
        'volumes_anime': '漫画の対応話数は放送に合わせて確認',
        'read_order': '漫画1巻から',
        'amazon_search': 'きみが死ぬまで恋をしたい 漫画',
        'tags': ['恋愛', 'SF'],
        'watchers_count': 7400,
    },
    {
        'title': '株式会社マジルミエ 第2期',
        'source_type': 'manga',
        'source_title': '株式会社マジルミエ',
        'volumes_anime': '第2期は漫画続編',
        'read_order': '1巻から',
        'amazon_search': '株式会社マジルミエ 漫画',
        'tags': ['コメディ', '魔法少女'],
        'watchers_count': 7200,
    },
    {
        'title': '正反対な君と僕 第2期',
        'source_type': 'manga',
        'source_title': '正反対な君と僕',
        'volumes_anime': '第2期は漫画続編',
        'read_order': '1巻から',
        'amazon_search': '正反対な君と僕 漫画',
        'tags': ['ラブコメ', '日常'],
        'watchers_count': 7000,
    },
    {
        'title': '攻殻機動隊 THE GHOST IN THE SHELL',
        'source_type': 'manga',
        'source_title': '攻殻機動隊',
        'volumes_anime': '原作漫画をベースにした劇場/新作',
        'read_order': '士郎正宗の漫画から',
        'amazon_search': '攻殻機動隊 漫画',
        'tags': ['SF', '名作'],
        'watchers_count': 6900,
    },
    {
        'title': '天幕のジャードゥーガル',
        'source_type': 'manga',
        'source_title': '天幕のジャードゥーガル',
        'volumes_anime': '漫画対応巻は放送開始後に追記推奨',
        'read_order': '漫画1巻から',
        'amazon_search': '天幕のジャードゥーガル 漫画',
        'tags': ['歴史', 'グルメ'],
        'watchers_count': 6800,
    },
    {
        'title': 'クレバテスⅡ-魔獣の王と偽りの勇者伝承-',
        'source_type': 'web_novel',
        'source_title': 'クレバテス',
        'volumes_anime': '第2期は続編',
        'read_order': 'Web版または単行本から',
        'amazon_search': 'クレバテス 漫画',
        'tags': ['ファンタジー', 'バトル'],
        'watchers_count': 6700,
    },
    {
        'title': 'スーパーの裏でヤニ吸うふたり',
        'source_type': 'manga',
        'source_title': 'スーパーの裏でヤニ吸うふたり',
        'volumes_anime': '漫画1〜2巻相当が多い',
        'read_order': '1巻から。短編寄り',
        'amazon_search': 'スーパーの裏でヤニ吸うふたり 漫画',
        'tags': ['日常', 'ラブコメ'],
        'watchers_count': 6600,
    },
    {
        'title': '追放された転生重騎士はゲーム知識で無双する',
        'source_type': 'light_novel',
        'source_title': '追放された転生重騎士はゲーム知識で無双する',
        'volumes_anime': '第1期はラノベ序盤',
        'read_order': '1巻から',
        'amazon_search': '追放された転生重騎士 ラノベ',
        'tags': ['異世界', 'ファンタジー'],
        'watchers_count': 6500,
    },
    {
        'title': 'ワールド イズ ダンシング',
        'source_type': 'original',
        'source_title': '',
        'volumes_anime': 'オリジナル作品',
        'read_order': '原作なし。アニメ単体で楽しむ',
        'amazon_search': '',
        'tags': ['スポーツ', 'オリジナル'],
        'watchers_count': 6400,
    },
    {
        'title': '二十世紀電氣目録-ユーレカ・エヴリカ-',
        'source_type': 'other',
        'source_title': '二十世紀電氣目録',
        'volumes_anime': '京アニ作品（原作形式は要確認）',
        'read_order': '公式情報を確認',
        'amazon_search': '二十世紀電氣目録',
        'tags': ['SF', '京アニ'],
        'watchers_count': 6300,
    },
    {
        'title': 'ワンパンマン 第3期',
        'source_type': 'manga',
        'source_title': 'ワンパンマン',
        'volumes_anime': '第3期は漫画「怪人協会編」後半〜（第1・2期は1〜16巻相当が目安）',
        'read_order': '漫画1巻から。アニメ2期まで見た人は17巻前後からも可',
        'amazon_search': 'ワンパンマン 漫画',
        'tags': ['バトル', 'ギャグ', '少年漫画'],
        'watchers_count': 9700,
    },
]

rows = []
for w in WORKS:
    work_id = slugify(w['title'])
    rows.append({
        'id': work_id,
        'share_slug': SHARE_SLUGS.get(w['title']) or share_slugify(w['title'], work_id),
        'season': SEASON,
        'status': 'upcoming',
        'media': 'tv',
        'memo': '',
        'official_url': '',
        **w,
    })

save_works(rows)
print(f'seeded {len(rows)} works -> data/works.json')
